### ISSUE TITLE
Make it possible to add the boilerplate noise on top of an existing project

### ISSUE THREAD

**Issue by MedUnes** [MedUnes/noise-php#5]
There should be a possibility to add the boilerplate and test configs on top of an existing project, without having to do it the other way around, i.e create noise project and copy the existing one to it.

**Comment by yarimadam** [comment]
How can both projects composer.json play together nicely? (eg: Noise + Symfony)

There are two options I can think of:

**1. Merging both projects composer.json into one:** This is tricky. Having two different project's dependencies into one composer.json can cause lots of version constraint problems. Plus, this way you will have two projects merged and this will also cause other problems like individual upgrading of projects.

**2. Maintaining two separate composer.json:** This sounds more logical since you can have both projects separated. However, this approach raises another question in my mind: If the framework project will have its own composer.json file what would noise's composer.json responsible for?

The usual approach for most PHP projects is to have almost all (dev) dependencies bundled within the project. However noise perspective is a little bit different. It separates some dev dependencies (mostly QA tools) outside of the main project. I'm not sure this approach can have acceptance by users. This is definitely different.

**Comment by MedUnes** [comment]
so I believe, till now at list, this skeleton is meant to be a starter kit instead of an addon on top of an existing project, so will close this issue.
